[package]
name = "alphabet-squared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.24", features = ["derive"] }
glam = "0.23.0"
opencascade = "0.2.0"
